databases:
    - name: adonis-pg-database
      user: lucid
      plan: free
      region: frankfurt
      ipAllowList: [] # only allow internal connections
services:
    # Redis set up
    - type: redis
      name: adonis-redis
      ipAllowList: [] # only allow internal connections
      region: frankfurt # optional (defaults to oregon)
      plan: free # optional (defaults to starter)
      maxmemoryPolicy: allkeys-lru # optional (defaults to allkeys-lru)
    # Adonis API
    - type: web
      name: adonis-api
      env: node
      region: frankfurt
      plan: free
      startCommand: yarn install --production=false && yarn build:tsc && cd ./packages/server && yarn migrate:force && yarn build && cd ./build && yarn start # run on deploy
      envVars:
          # Plain constants
          - key: NODE_ENV
            value: production
          - key: SESSION_DRIVER
            value: cookie
          - key: CACHE_VIEWS
            value: false
          # Redis env vars
          - key: REDIS_CONNECTION
            value: local
          - key: REDIS_HOST
            fromService:
                type: redis
                name: adonis-redis
                property: host
          - key: REDIS_PORT
            fromService:
                type: redis
                name: adonis-redis
                property: port
          - key: REDIS_PASSWORD
            value: unused-password
          # Pg env vars
          - key: DB_CONNECTION
            value: pg
          - key: PG_DB_NAME
            value: adonis_pg_database
          - key: PG_HOST
            fromDatabase:
                name: adonis-pg-database
                property: host
          - key: PG_PORT
            fromDatabase:
                name: adonis-pg-database
                property: port
          - key: PG_PASSWORD
            fromDatabase:
                name: adonis-pg-database
                property: password
          - key: PG_USER
            fromDatabase:
                name: adonis-pg-database
                property: user
          # TODO define SMTP / EMAIL SERVICES infos below as sync false etc
          - key: SMTP_HOST
            value: undefined
          - key: SMTP_PORT
            value: 42
          - key: SMTP_USERNAME
            value: username
          - key: SMTP_PASSWORD
            value: password
          # Google secrets
          - key: GOOGLE_CLIENT_ID
            sync: false
          - key: GOOGLE_CLIENT_SECRET
            sync: false
          - key: GOOGLE_API_KEY
            sync: false
          - key: GOOGLE_GEOCODING_API_KEY
            sync: false
          # Other secrets
          - key: TEMPORAL_ADONIS_KEY
            sync: false
          - key: APP_KEY
            sync: false
