// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RecordHeartbeatWrapperType is an autogenerated mock type for the RecordHeartbeatWrapperType type
type RecordHeartbeatWrapperType struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, details
func (_m *RecordHeartbeatWrapperType) Execute(ctx context.Context, details ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, details...)
	_m.Called(_ca...)
}
