version: '3'
services:
    database:
        image: 'postgres:latest'
        ports:
            - ${PG_PORT}:${PG_PORT}
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB_NAME}
        volumes:
            - database-data:/var/lib/postgresql/data/
    redis:
        image: redis:4.0.5-alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        hostname: local
        ports:
            - '${REDIS_PORT}:${REDIS_PORT}'
        networks:
            - redis-net
        volumes:
            - redis-data:/data

networks:
    redis-net:

volumes:
    redis-data:
    database-data:
