version: '3'
services:
    database:
        image: 'postgres:latest'
        ports:
            - ${PG_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_DB: ${PG_DB_NAME}
        volumes:
            - database-data:/var/lib/postgresql/data/
    database-test:
        image: 'postgres:latest'
        ports:
            - ${PG_TEST_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${PG_TEST_PASSWORD}
            POSTGRES_USER: ${PG_TEST_USER}
            POSTGRES_DB: ${PG_TEST_DB_NAME}
        volumes:
            - database-test-data:/var/lib/postgresql/data/
    redis:
        image: redis:4.0.5-alpine
        command: redis-server --requirepass ${REDIS_PASSWORD}
        hostname: local
        ports:
            - ${REDIS_PORT}:6379
        networks:
            - redis-net
        volumes:
            - redis-data:/data

networks:
    redis-net:

volumes:
    redis-data:
    database-data:
    database-test-data:
